# version: "3.8"
# services:
#   # Docker connection string for local machine: postgres://postgres:postgres@localhost:5432/

#   postgres:
#     image: postgres:13.5 # 1
#     restart: always
#     environment: # 2
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=phantomu
#       - POSTGRES_DB=db_flash
#       - POSTGRES_HOST=localhost
#     volumes: # 3
#       - postgres:/var/lib/postgresql/data
#     ports:
#       - "5432:5432" # 4

# volumes:
#   postgres:

version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
