/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Mutation: {};
  Query: {};
  newAdmin: { // root type
    email: string; // String!
    firstName: string; // String!
    id?: string | null; // String
    password: string; // String!
    secondName: string; // String!
    users?: Array<NexusGenRootTypes['newUser'] | null> | null; // [newUser]
  }
  newUser: { // root type
    adminId: string; // String!
    email: string; // String!
    firstName: string; // String!
    id?: string | null; // String
    password: string; // String!
    secondName: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    create_admin: NexusGenRootTypes['newAdmin']; // newAdmin!
    delete_admin: string; // String!
    update_admin: NexusGenRootTypes['newAdmin']; // newAdmin!
  }
  Query: { // field return type
    allAdmins: NexusGenRootTypes['newAdmin'][]; // [newAdmin!]!
    oneAdmin: NexusGenRootTypes['newAdmin']; // newAdmin!
  }
  newAdmin: { // field return type
    email: string; // String!
    firstName: string; // String!
    id: string | null; // String
    password: string; // String!
    secondName: string; // String!
    users: Array<NexusGenRootTypes['newUser'] | null> | null; // [newUser]
  }
  newUser: { // field return type
    adminId: string; // String!
    email: string; // String!
    firstName: string; // String!
    id: string | null; // String
    password: string; // String!
    secondName: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    create_admin: 'newAdmin'
    delete_admin: 'String'
    update_admin: 'newAdmin'
  }
  Query: { // field return type name
    allAdmins: 'newAdmin'
    oneAdmin: 'newAdmin'
  }
  newAdmin: { // field return type name
    email: 'String'
    firstName: 'String'
    id: 'String'
    password: 'String'
    secondName: 'String'
    users: 'newUser'
  }
  newUser: { // field return type name
    adminId: 'String'
    email: 'String'
    firstName: 'String'
    id: 'String'
    password: 'String'
    secondName: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    create_admin: { // args
      email: string; // String!
      firstName: string; // String!
      password: string; // String!
      secondName: string; // String!
    }
    delete_admin: { // args
      id: string; // String!
    }
    update_admin: { // args
      email: string; // String!
      id: string; // String!
      password: string; // String!
    }
  }
  Query: {
    oneAdmin: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}